-- MySQL Script generated by MySQL Workbench
-- Tue Sep  8 09:20:22 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema agrofacil_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema agrofacil_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `agrofacil_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `agrofacil_db` ;

-- -----------------------------------------------------
-- Table `agrofacil_db`.`TB_Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agrofacil_db`.`TB_Usuarios` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(225) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `hash_senha` VARCHAR(225) NOT NULL,
  `data_nasc` DATE NULL,
  `estado` CHAR(2) NULL,
  `data_cadastro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agrofacil_db`.`TB_Areas_Irrigacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agrofacil_db`.`TB_Areas_Irrigacao` (
  `id` INT UNSIGNED NOT NULL,
  `id_usuario` INT UNSIGNED NOT NULL,
  `nome_area` VARCHAR(20) NOT NULL,
  `tamanho` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `id_usuario_INDEX` (`id_usuario` ASC) VISIBLE,
  UNIQUE INDEX `nome_area_UNIQUE` (`nome_area` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_areas_irrigacao`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `agrofacil_db`.`TB_Usuarios` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agrofacil_db`.`TB_Tarefas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agrofacil_db`.`TB_Tarefas` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome_tarefa` VARCHAR(45) NOT NULL,
  `descricao` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `nome_tarefa_UNIQUE` (`nome_tarefa` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agrofacil_db`.`TB_Progresso_Tarefas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agrofacil_db`.`TB_Progresso_Tarefas` (
  `id_usuario` INT UNSIGNED NOT NULL,
  `id_tarefa` INT UNSIGNED NOT NULL,
  `esta_feito` ENUM("S", "N") NOT NULL DEFAULT 'N',
  PRIMARY KEY (`id_tarefa`, `id_usuario`),
  INDEX `id_tarefa_INDEX` (`id_tarefa` ASC) VISIBLE,
  INDEX `id_usuario_INDEX` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_progresso`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `agrofacil_db`.`TB_Usuarios` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tarefas_progresso`
    FOREIGN KEY (`id_tarefa`)
    REFERENCES `agrofacil_db`.`TB_Tarefas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agrofacil_db`.`TB_Sensores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agrofacil_db`.`TB_Sensores` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_usuario` INT UNSIGNED NOT NULL,
  `id_area` INT UNSIGNED NULL,
  `nome_sensor` VARCHAR(45) NOT NULL,
  `tipo_sensor` ENUM("TEMP", "COND", "UMID") NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `id_usuario_INDEX` (`id_usuario` ASC) VISIBLE,
  INDEX `id_area_INDEX` (`id_area` ASC) VISIBLE,
  UNIQUE INDEX `nome_sensor_UNIQUE` (`nome_sensor` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_sensores`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `agrofacil_db`.`TB_Usuarios` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_areas_irrigacao_sensores`
    FOREIGN KEY (`id_area`)
    REFERENCES `agrofacil_db`.`TB_Areas_Irrigacao` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agrofacil_db`.`TB_Leituras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agrofacil_db`.`TB_Leituras` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_sensor` INT UNSIGNED NOT NULL,
  `tipo_leitura` ENUM("TEMP", "COND", "UMID") NOT NULL,
  `valor` FLOAT NOT NULL,
  `datahora_leitura` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `id_sensor_INDEX` (`id_sensor` ASC) VISIBLE,
  CONSTRAINT `fk_sensores_leituras`
    FOREIGN KEY (`id_sensor`)
    REFERENCES `agrofacil_db`.`TB_Sensores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
